# frontend/Dockerfile
FROM node:20 AS builder
WORKDIR /app

# Copy only package files first to install dependencies
COPY hahn-task/package*.json ./ 

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY hahn-task/ ./

# Build the app
RUN npm run build

# Serve with nginx
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
