version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8180:8180"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hahn
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hahn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
